In [2]:
from sklearn import datasets
import numpy as np

In [3]:
iris = datasets.load_iris()
print(iris)



{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [4]:
# 1_DiscriminantFunc_K-Means_widroHoffman

import numpy as np


class Widro_Hoff_Learning_Algorithm:

    def __init__(self, learning_rate=0.01, n_iters=12):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.activation_func = self._unit_step_func
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape

        # init parameters
        self.weights = np.zeros(n_features)
        self.bias = 0

        y_ = np.array([1 if i > 0 else 0 for i in y])

        for _ in range(self.n_iters):
            
            for idx, x_i in enumerate(X):

                linear_output = np.dot(x_i, self.weights) + self.bias
                y_predicted = self.activation_func(linear_output)
                
                # Perceptron update rule
                update = self.lr * (y_[idx] - y_predicted)

                self.weights += update * x_i
                self.bias += update

    def predict(self, X):
        linear_output = np.dot(X, self.weights) + self.bias
        y_predicted = self.activation_func(linear_output)
        return y_predicted

    def _unit_step_func(self, x):
        return np.where(x>=0, 1, 0)

In [99]:
# Quiz , Perceptron , Sequential Delta Learning algorithm.
# test

import numpy as np

class Sequential_Delta_Learning_Algorithm:

    def __init__(self, Learning_rate = 1.0 , weight_initial_1 = -7.5, weight_initial_2 = 1.5, theta=-3.5,iterations= 5, target_output= None):
        self.lr =  Learning_rate
        self.w1 = weight_initial_1
        self.w2 = weight_initial_2
        self.__theta= theta
        self.iter = iterations
        self.initial_weights = np.array([-theta , weight_initial_1, weight_initial_2])
        self.updated_weights = self.initial_weights
        self.t = target_output
        self.activationFunction = self.unit_Step_Activation_Function


    def fit(self, x, t , w):
        # e.g : w = [-theta,w1,w2] x = [1,x1,x2,x3,x4]
        # Loop {  
        #   y(predict) = H(wx)
        #   update w 
        # }
        """
        t is the taget output
        we need feature vectors = x , weights = w , and t
        """
        #INIT params
        # x ,t 
        # t[i] - current target output/class
        # x[i] - current feature vector
        Number_of_samples , cols = x.shape
        
        self.updated_weights = w
        print(f"initial weights : {self.updated_weights}")
        
        
        
        for i in range(self.iter):
            """ Epoch Loop"""
            
            for j in range(Number_of_samples):
                print()
                print()
                print(f"------------ iter {j} ---------------")
                print()
                print()
                print(f"current feature vector : \n {x[j]}")
                print(f"current target output : \n {t[j]}")
            
           
                temp = np.insert(x[j], 0, 1)
                print(f"current feature vector Normalised: \n {temp}")
                  
                y_predicted = self.predict(self.updated_weights, temp)
                print(f"predicted class label : {y_predicted}")

                #Weight Update Rule
                # (t -y)
                error = t[j] - y_predicted
                change = (self.lr * error ) * temp
                self.updated_weights += change
                print(f"Updated weights : {self.updated_weights}")
            
                  
        print("done")


    def predict(self, w,x):
        # w and x are numpy arrays simulating matrix of weights and vectors
        Matrix_product = w @ x
        print(f"Matrix Product : {Matrix_product}")
        y_predicted = self.activationFunction(Matrix_product)
        return y_predicted



    def unit_Step_Activation_Function(self, x):
        if (x < 0):
#             print(0)
            return 0
#         elif (x == 0):
#             print(0.5)
#             return 0.5
        else:
#             print(1)
            return 1

In [100]:
x = Sequential_Delta_Learning_Algorithm()

#Test Case

dataset = np.array([[0,0],
                    [0,1],
                    [1,0],
                    [1,1]])
target = np.array([0,0,0,1])
weights = np.array([0.5,1,1])
x.fit(dataset, target, weights)

# print(dataset[0])

# print(np.insert(dataset[0], 0, 1))


initial weights : [0.5 1.  1. ]


------------ iter 0 ---------------


current feature vector : 
 [0 0]
current target output : 
 0
current feature vector Normalised: 
 [1 0 0]
Matrix Product : 0.5
predicted class label : 1
Updated weights : [-0.5  1.   1. ]


------------ iter 1 ---------------


current feature vector : 
 [0 1]
current target output : 
 0
current feature vector Normalised: 
 [1 0 1]
Matrix Product : 0.5
predicted class label : 1
Updated weights : [-1.5  1.   0. ]


------------ iter 2 ---------------


current feature vector : 
 [1 0]
current target output : 
 0
current feature vector Normalised: 
 [1 1 0]
Matrix Product : -0.5
predicted class label : 0
Updated weights : [-1.5  1.   0. ]


------------ iter 3 ---------------


current feature vector : 
 [1 1]
current target output : 
 1
current feature vector Normalised: 
 [1 1 1]
Matrix Product : -0.5
predicted class label : 0
Updated weights : [-0.5  2.   1. ]


------------ iter 0 ---------------


current featur

In [105]:
# Quiz , Perceptron , Sequential Delta Learning algorithm.
# q1

import numpy as np

class Sequential_Delta_Learning_Algorithm:

    def __init__(self, Learning_rate = 1.0 , weight_initial_1 = -7.5, weight_initial_2 = 1.5, theta=-3.5,iterations= 2, target_output= None):
        self.lr =  Learning_rate
        self.w1 = weight_initial_1
        self.w2 = weight_initial_2
        self.__theta= theta
        self.iter = iterations
        self.initial_weights = np.array([-theta , weight_initial_1, weight_initial_2])
        self.updated_weights = self.initial_weights
        self.t = target_output
        self.activationFunction = self.unit_Step_Activation_Function


    def fit(self, x, t):
        # e.g : w = [-theta,w1,w2] x = [1,x1,x2,x3,x4]
        # Loop {  
        #   y(predict) = H(wx)
        #   update w 
        # }
        """
        t is the taget output
        we need feature vectors = x , weights = w , and t
        """
        #INIT params
        # x ,t 
        # t[i] - current target output/class
        # x[i] - current feature vector
        Number_of_samples , cols = x.shape
        print(f"initial weights : {self.updated_weights}")
        print(f"initial weights : {self.updated_weights.dtype}")
        
        
        
        for i in range(self.iter):
            """ Epoch Loop"""
            
            for j in range(Number_of_samples):
                print()
                print()
                print(f"------------ iter {j} ---------------")
                print()
                print()
                print(f"current feature vector : \n {x[j]}")
                print(f"current target output : \n {t[j]}")
            
           
                temp = np.insert(x[j], 0, 1)
                print(f"current feature vector Normalised: \n {temp}")
                  
                y_predicted = self.predict(self.updated_weights, temp)
                print(f"predicted class label : {y_predicted}")

                #Weight Update Rule
                # (t -y)
                error = t[j] - y_predicted
                change = (self.lr * error ) * temp
                self.updated_weights += change
                print(f"Updated weights : {self.updated_weights}")
            
                  
        print("done")


    def predict(self, w,x):
        # w and x are numpy arrays simulating matrix of weights and vectors
        Matrix_product = w @ x
        print(f"Matrix_product : {Matrix_product}")
        y_predicted = self.activationFunction(Matrix_product)
        return y_predicted



    def unit_Step_Activation_Function(self, x):
        if (x < 0):
#             print(0)
            return 0.0
        elif (x == 0):
            print(0.5)
            return 0.5
        else:
#             print(1)
            return 1.0

In [106]:
x = Sequential_Delta_Learning_Algorithm()

#Test Case

dataset = np.array([[0.0,2.0],
                    [1.0,2.0],
                    [2.0,1.0],
                    [-3.0,1.0],
                    [-2.0,-1.0],
                    [-3.0,-2.0]])
target = np.array([1,1,1,0,0,0])
x.fit(dataset, target)

initial weights : [ 3.5 -7.5  1.5]
initial weights : float64


------------ iter 0 ---------------


current feature vector : 
 [0. 2.]
current target output : 
 1
current feature vector Normalised: 
 [1. 0. 2.]
Matrix_product : 6.5
predicted class label : 1.0
Updated weights : [ 3.5 -7.5  1.5]


------------ iter 1 ---------------


current feature vector : 
 [1. 2.]
current target output : 
 1
current feature vector Normalised: 
 [1. 1. 2.]
Matrix_product : -1.0
predicted class label : 0.0
Updated weights : [ 4.5 -6.5  3.5]


------------ iter 2 ---------------


current feature vector : 
 [2. 1.]
current target output : 
 1
current feature vector Normalised: 
 [1. 2. 1.]
Matrix_product : -5.0
predicted class label : 0.0
Updated weights : [ 5.5 -4.5  4.5]


------------ iter 3 ---------------


current feature vector : 
 [-3.  1.]
current target output : 
 0
current feature vector Normalised: 
 [ 1. -3.  1.]
Matrix_product : 23.5
predicted class label : 1.0
Updated weights : [ 4.5 -1

In [88]:
# # Quiz , Perceptron , Sequential Delta Learning algorithm.
# q2

import numpy as np

class Sequential_Delta_Learning_Algorithm:

    def __init__(self, Learning_rate = 0.10 , 
                 weight_initial_1 = 0.5, weight_initial_2 = 1.5,
                 weight_initial_3 = -2.5, weight_initial_4 = 2.5,
                 theta=-0.5 , 
                 iterations= 2, target_output= None):
        
        self.lr =  Learning_rate
        
        self.w1 = weight_initial_1
        self.w2 = weight_initial_2
        self.w3 = weight_initial_3
        self.w4 = weight_initial_4
        
        self.__theta= theta
        
        self.iter = iterations
        
        self.initial_weights = np.array([-theta , weight_initial_1, weight_initial_2, weight_initial_3, weight_initial_4])
        self.initial_weight = np.array([-theta , weight_initial_1, weight_initial_2, weight_initial_3, weight_initial_4])
        self.updated_weights = self.initial_weights
        
        self.t = target_output
        
        self.correctbeforelearning = self.correctSamplesBeforeLearning
        self.correctafterlearning = self.correctSamplesAfterLearning
        self.activationFunction = self.unit_Step_Activation_Function
        self.finalWeightAfterLearning = None


    def fit(self, x, t):
        # e.g : w = [-theta,w1,w2] x = [1,x1,x2,x3,x4]
        # Loop {  
        #   y(predict) = H(wx)
        #   update w 
        # }
        """
        t is the taget output
        we need feature vectors = x , weights = w , and t
        """
        #INIT params
        # x ,t 
        # t[i] - current target output/class
        # x[i] - current feature vector
        Number_of_samples , cols = x.shape
        print(f"initial weights : {self.updated_weights}")
        print(f"initial weights : {self.updated_weights.dtype}")
        
        
        
        for i in range(self.iter):
            """ Epoch Loop"""
            
            for j in range(Number_of_samples):
                print()
                print()
                print(f"------------ iter {j} ---------------")
                print()
                print()
                print(f"current feature vector : \n {x[j]}")
                print(f"current target output : \n {t[j]}")
            
           
                temp = np.insert(x[j], 0, 1)
                print(f"current feature vector Normalised: \n {temp}")
                  
                y_predicted = self.predict(self.updated_weights, temp)
                print(f"predicted class label : {y_predicted}")

                #Weight Update Rule
                # (t -y)
                error = t[j] - y_predicted
                change = (self.lr * error ) * temp
                self.updated_weights += change
                print(f"Updated weights : {self.updated_weights}")
            
        self.finalWeightAfterLearning = self.updated_weights
        print("----------------------------")
        print(f"Updated Weights :  {self.finalWeightAfterLearning}")
        print("----------------------------")
        print(f"Initial Weights : {self.initial_weight}")
        print("done")
        
        Percentage_Before = self.correctbeforelearning(self.initial_weight,Number_of_samples,x,t)
        print()
        print("------------------------------")
        print(f"% correctly classified before learning : {Percentage_Before}")
        print()
        
        Percentage_After = self.correctafterlearning(self.finalWeightAfterLearning,Number_of_samples,x,t)
        print()
        print("------------------------------")
        print(f"% correctly classified after learning : {Percentage_After}")
        print()
        


    def predict(self, w,x):
        # w and x are numpy arrays simulating matrix of weights and vectors
        Matrix_product = w @ x
        print(f"Matrix_product : {Matrix_product}")
        y_predicted = self.activationFunction(Matrix_product)
        return y_predicted



    def unit_Step_Activation_Function(self, x):
        if (x < 0):
#             print(0)
            return 0.0
        elif (x == 0):
            print(0.5)
            return 0.5
        else:
#             print(1)
            return 1.0

    def correctSamplesBeforeLearning(self,w_initial,No_of_samples,X,target):
        correctly_Predicted_Samples = 0
        for i in range(No_of_samples):
            temp = np.insert(X[i], 0, 1)
#             print(f"current feature vector Normalised: \n {temp}")
                  
            y_predicted = self.predict(w_initial, temp)
#             print(f"predicted class label : {y_predicted}")
            if (target[i] == y_predicted):
                correctly_Predicted_Samples += 1
            
        percentage = (correctly_Predicted_Samples / No_of_samples) * 100
        return percentage
    
    def correctSamplesAfterLearning(self,w_updated,No_of_samples,X,target):
        correctly_Predicted_Samples = 0
        for i in range(No_of_samples):
            temp = np.insert(X[i], 0, 1)
#             print(f"current feature vector Normalised: \n {temp}")
                  
            y_predicted = self.predict(w_updated, temp)
#             print(f"predicted class label : {y_predicted}")
            if (target[i] == y_predicted):
                correctly_Predicted_Samples += 1
            
        percentage = (correctly_Predicted_Samples / No_of_samples) * 100
        return percentage
            

In [89]:
#print(iris)
iris_Data = iris.data
target = iris.target
target_Names = iris.target_names
Description = iris.DESCR
Feature_Names= iris.feature_names
print(iris_Data.size)


600


In [90]:
rows , cols = iris_Data.shape
print(rows)

150


In [91]:
print(Description)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [92]:
# print(target)
print(iris_Data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [93]:
new_target = [1 if i == 0 else 0 for i in target ]
print(new_target)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [94]:
x = Sequential_Delta_Learning_Algorithm()
x.fit(iris_Data, new_target)

initial weights : [ 0.5  0.5  1.5 -2.5  2.5]
initial weights : float64


------------ iter 0 ---------------


current feature vector : 
 [5.1 3.5 1.4 0.2]
current target output : 
 1
current feature vector Normalised: 
 [1.  5.1 3.5 1.4 0.2]
Matrix_product : 5.300000000000001
predicted class label : 1.0
Updated weights : [ 0.5  0.5  1.5 -2.5  2.5]


------------ iter 1 ---------------


current feature vector : 
 [4.9 3.  1.4 0.2]
current target output : 
 1
current feature vector Normalised: 
 [1.  4.9 3.  1.4 0.2]
Matrix_product : 4.45
predicted class label : 1.0
Updated weights : [ 0.5  0.5  1.5 -2.5  2.5]


------------ iter 2 ---------------


current feature vector : 
 [4.7 3.2 1.3 0.2]
current target output : 
 1
current feature vector Normalised: 
 [1.  4.7 3.2 1.3 0.2]
Matrix_product : 4.9
predicted class label : 1.0
Updated weights : [ 0.5  0.5  1.5 -2.5  2.5]


------------ iter 3 ---------------


current feature vector : 
 [4.6 3.1 1.5 0.2]
current target output : 
 1
cur

current target output : 
 0
current feature vector Normalised: 
 [1.  6.8 2.8 4.8 1.4]
Matrix_product : -8.608
predicted class label : 0.0
Updated weights : [ 0.4  -0.2   1.18 -2.97  2.36]


------------ iter 77 ---------------


current feature vector : 
 [6.7 3.  5.  1.7]
current target output : 
 0
current feature vector Normalised: 
 [1.  6.7 3.  5.  1.7]
Matrix_product : -8.238000000000003
predicted class label : 0.0
Updated weights : [ 0.4  -0.2   1.18 -2.97  2.36]


------------ iter 78 ---------------


current feature vector : 
 [6.  2.9 4.5 1.5]
current target output : 
 0
current feature vector Normalised: 
 [1.  6.  2.9 4.5 1.5]
Matrix_product : -7.203
predicted class label : 0.0
Updated weights : [ 0.4  -0.2   1.18 -2.97  2.36]


------------ iter 79 ---------------


current feature vector : 
 [5.7 2.6 3.5 1. ]
current target output : 
 0
current feature vector Normalised: 
 [1.  5.7 2.6 3.5 1. ]
Matrix_product : -5.7070000000000025
predicted class label : 0.0
Updated wei

current feature vector Normalised: 
 [1.  5.9 3.  5.1 1.8]
Matrix_product : -8.139
predicted class label : 0.0
Updated weights : [ 0.4  -0.2   1.18 -2.97  2.36]


------------ iter 0 ---------------


current feature vector : 
 [5.1 3.5 1.4 0.2]
current target output : 
 1
current feature vector Normalised: 
 [1.  5.1 3.5 1.4 0.2]
Matrix_product : -0.1760000000000006
predicted class label : 0.0
Updated weights : [ 0.5   0.31  1.53 -2.83  2.38]


------------ iter 1 ---------------


current feature vector : 
 [4.9 3.  1.4 0.2]
current target output : 
 1
current feature vector Normalised: 
 [1.  4.9 3.  1.4 0.2]
Matrix_product : 3.123
predicted class label : 1.0
Updated weights : [ 0.5   0.31  1.53 -2.83  2.38]


------------ iter 2 ---------------


current feature vector : 
 [4.7 3.2 1.3 0.2]
current target output : 
 1
current feature vector Normalised: 
 [1.  4.7 3.2 1.3 0.2]
Matrix_product : 3.6500000000000004
predicted class label : 1.0
Updated weights : [ 0.5   0.31  1.53 -2.83 

Updated weights : [ 0.5   0.31  1.53 -2.83  2.38]


------------ iter 71 ---------------


current feature vector : 
 [6.1 2.8 4.  1.3]
current target output : 
 0
current feature vector Normalised: 
 [1.  6.1 2.8 4.  1.3]
Matrix_product : -1.5510000000000015
predicted class label : 0.0
Updated weights : [ 0.5   0.31  1.53 -2.83  2.38]


------------ iter 72 ---------------


current feature vector : 
 [6.3 2.5 4.9 1.5]
current target output : 
 0
current feature vector Normalised: 
 [1.  6.3 2.5 4.9 1.5]
Matrix_product : -4.019000000000002
predicted class label : 0.0
Updated weights : [ 0.5   0.31  1.53 -2.83  2.38]


------------ iter 73 ---------------


current feature vector : 
 [6.1 2.8 4.7 1.2]
current target output : 
 0
current feature vector Normalised: 
 [1.  6.1 2.8 4.7 1.2]
Matrix_product : -3.7700000000000014
predicted class label : 0.0
Updated weights : [ 0.5   0.31  1.53 -2.83  2.38]


------------ iter 74 ---------------


current feature vector : 
 [6.4 2.9 4.3 1.3]
c

------------ iter 141 ---------------


current feature vector : 
 [6.9 3.1 5.1 2.3]
current target output : 
 0
current feature vector Normalised: 
 [1.  6.9 3.1 5.1 2.3]
Matrix_product : -7.7540000000000004
predicted class label : 0.0
Updated weights : [ 0.4  -0.2   1.28 -3.13  2.27]


------------ iter 142 ---------------


current feature vector : 
 [5.8 2.7 5.1 1.9]
current target output : 
 0
current feature vector Normalised: 
 [1.  5.8 2.7 5.1 1.9]
Matrix_product : -8.954
predicted class label : 0.0
Updated weights : [ 0.4  -0.2   1.28 -3.13  2.27]


------------ iter 143 ---------------


current feature vector : 
 [6.8 3.2 5.9 2.3]
current target output : 
 0
current feature vector Normalised: 
 [1.  6.8 3.2 5.9 2.3]
Matrix_product : -10.11
predicted class label : 0.0
Updated weights : [ 0.4  -0.2   1.28 -3.13  2.27]


------------ iter 144 ---------------


current feature vector : 
 [6.7 3.3 5.7 2.5]
current target output : 
 0
current feature vector Normalised: 
 [1.  6.7 